services:
  pnpm:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.pnpm
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database: 
    image: "postgres:17.5"
    environment:
      POSTGRES_PASSWORD: Ahmedxd1
      POSTGRES_USER: ahmed 
      POSTGRES_DB: subscriptions 
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data: