services:
  pnpm:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.pnpm
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file: ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules